### ISSUE TITLE
Update to 1.20.1 and 1.20.2

### ISSUE THREAD

**Issue by Shadowblitz16** [Suiranoil/SkinRestorer#10]

**Comment by Suiranoil** [comment]
The version 1.2.3 works fine on 1.20-1.20.1, I updated the mod to version 1.2.4 which works fine on 1.20.2

**Comment by kacperc99** [comment]
@Suiranoil  it is not properly updated/labeled on curseforge and 1.2.4 still figures as a mod for 1.20.1 version of minecraft

**Comment by kacperc99** [comment]
also an attempt to launch a server pops this error out
https://pastebin.com/HxXNhjVG

**Comment by Suiranoil** [comment]
@kacperc99 The version for 1.20.2 on curseforge is under manual review for some reason so it is not visible. You can download it from modrinth: <https://modrinth.com/mod/skinrestorer/version/1.2.4+1.20.2>

**Comment by kacperc99** [comment]
Then I am screwed, cuz modritnh one is nto available on Aternos

**Comment by Suiranoil** [comment]
Curseforge approved the 1.20.2 version, you can now see and download it
<https://legacy.curseforge.com/minecraft/mc-mods/skinrestorer/files/4778752>

**Comment by kacperc99** [comment]
Ayyy, thanks
