### ISSUE TITLE
Web part of the /skin isnt working

### ISSUE THREAD

**Issue by SelimGOZ** [Suiranoil/SkinRestorer#14]
i keep trying /skin set web https://namemc.com/skin/6b6e375738867805 Selimpro but it keeps saying but found traling data
![image](https://github.com/Suiranoil/SkinRestorer/assets/110635921/567189ca-be0b-498d-95d0-fe569f5adc79)

**Comment by Suiranoil** [comment]
You should put link in quotes, also it should be a link directly to png file.
On namemc you can get link to a file by right clicking on download button and pressing 'Copy link address'.
So the command you provided should look like this: /skin set web "https://s.namemc.com/i/6b6e375738867805.png" Selimpro

**Comment by TypedKibbles960** [comment]
> You should put link in quotes, also it should be a link directly to png file. On namemc you can get link to a file by right clicking on download button and pressing 'Copy link address'. So the command you provided should look like this: /skin set web "https://s.namemc.com/i/6b6e375738867805.png" Selimpro

hey man, could you please include this in the readme file or mod description on the websites? cuz like i spent an hour trying to figure out how to use it until i came here
