### ISSUE TITLE
Url Error

### ISSUE THREAD

**Issue by MrCentipede1** [Suiranoil/SkinRestorer#17]
I cant type urls on the chat bar but ''mojang'' option works
![image](https://github.com/Suiranoil/SkinRestorer/assets/158461328/55b2adb8-b23b-41af-a632-255dcb19eee0)

**Comment by jack-mil** [comment]
I also have this issue. I think there is something with the url special character escaping? It works if you enclose the url in double quotes 
`"<url>"`
