### ISSUE TITLE
Update to 1.21 

### ISSUE THREAD

**Issue by shvecia** [Suiranoil/SkinRestorer#22]
PLEASE

**Comment by Suiranoil** [comment]
i have updated mod to 1.21: https://modrinth.com/mod/skinrestorer/version/1.2.6+1.21

**Comment by shvecia** [comment]
> i have updated mod to 1.21: https://modrinth.com/mod/skinrestorer/version/1.2.6+1.21

broken link

**Comment by Suiranoil** [comment]
fixed
