### ISSUE TITLE
skin restorer java class file error

### ISSUE THREAD

**Issue by eltiodarek** [Suiranoil/SkinRestorer#25]
-- MOD skinrestorer --
Details:
       	Mod File: /D:/SERVERS/server 1.20.4 NEOFORGE/mods/skin-restorer-2.0.0+1.20.3.jar
	Failure message: SkinRestorer has class loading errors
		java.lang.UnsupportedClassVersionError: neoforge/net/lionarius/skinrestorer/neoforge/SkinRestorerNeoForge has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
	Mod Version: 2.0.0+1.20.3
	Mod Issue URL: https://github.com/Suiranoil/SkinRestorer/issues
	Exception message: java.lang.UnsupportedClassVersionError: neoforge/net/lionarius/skinrestorer/neoforge/SkinRestorerNeoForge has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0                             -- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.10, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation

**Comment by Suiranoil** [comment]
Version 2.0.0 is compiled for Java 21, so you should use Java 21+ to run your server
