### ISSUE TITLE
Shows my IP Address to everyone.

### ISSUE THREAD

**Issue by Madcept** [Suiranoil/SkinRestorer#27]
On a private server with friends. But when multiple users are changing the skins the same time it pops up with my IP address. 

https://imgur.com/uH23gnv

And it shows for everyone, not just me. 

Any fix I can do?

**Comment by Suiranoil** [comment]
1. Error messages are only visible to you, no one else on the server can see them
2. 10.x.x.x ip is reserved for private networks and cannot be accessed from the internet, so nothing personal is getting "leaked". https://en.wikipedia.org/wiki/Reserved_IP_addresses
