### ISSUE TITLE
Does SkinRestorer support mods that add custom capes?

### ISSUE THREAD

**Issue by Itsporo** [Suiranoil/SkinRestorer#29]
- Does SkinRestorer support mods that add custom capes?

**Comment by Suiranoil** [comment]
I have not tested it with mods that add custom capes, so compatability with such mods is not guaranteed.

**Comment by Itsporo** [comment]
> I have not tested it with mods that add custom capes, so compatability with such mods is not guaranteed.

Ok, thank you!
