### ISSUE TITLE
how to use this

### ISSUE THREAD

**Issue by loogchin** [Suiranoil/SkinRestorer#3]
how to use /skin set web ?
pls answer

**Comment by Suiranoil** [comment]
/skin set web <classic|slim> "some.image.com/skin.png"
classic is steve model
slim is alex model
"some.image.com/skin.png" is url to your skin; "" are necessary

**Comment by loogchin** [comment]
> /skin set web <classic|slim> "some.image.com/skin.png" classic is steve model slim is alex model "some.image.com/skin.png" is url to your skin; "" are necessary

**Comment by loogchin** [comment]
> > /skin set web <classic|slim> "some.image.com/skin.png" classic is steve model slim is alex model "some.image.com/skin.png" is url to your skin; "" are necessary
