### ISSUE TITLE
Autofetch user skin from ely.by after player reconnect

### ISSUE THREAD

**Issue by dhhdhshdja** [Suiranoil/SkinRestorer#31]
Step to reproduce:
1) Set skin type in config to ely.by
2) Join server
3) Leave server
4) Change skin in ely.by account
5) Join server

Excepted behavior:
Skin should change on server

Real behavior:
Nothing happens

**Comment by Suiranoil** [comment]
This is the intended behavior.
Automatic fetching works only if player does not have skin set (e.g. when player joins offline server for the first time or if they reset their skin using `/skin reset`).
If you want to update your skin you should use command `/skin refresh`, which will refetch your skin from ely.by. Note that it takes couple of minutes for ely.by to actually update your skin.
