### ISSUE TITLE
Compatability with SkinShuffle?

### ISSUE THREAD

**Issue by IMB11** [Suiranoil/SkinRestorer#34]
Wondering if you'd be interested in adding compatibility for the skinshuffle refresh/swap skin packets - and the handshake packet;

https://github.com/IMB11/SkinShuffle/blob/main/src/main/java/com/mineblock11/skinshuffle/networking/HandshakePayload.java
https://github.com/IMB11/SkinShuffle/blob/main/src/main/java/com/mineblock11/skinshuffle/networking/SkinRefreshPayload.java
https://github.com/IMB11/SkinShuffle/blob/main/src/main/java/com/mineblock11/skinshuffle/networking/RefreshPlayerListEntryPayload.java

**Comment by WinsomeGuy** [comment]
@Suiranoil can we have some further enhancements to this feature? 

Currently, this feature only supports online accounts; by this, I mean the skin swap only works with the online accounts ( using skin shuffle mod) 

Can this feature be available for offline accounts as well? Thank you!
