### ISSUE TITLE
Suddenly stopped working on my end [1.21 Fabric]

### ISSUE THREAD

**Issue by SnoopyCodeX** [Suiranoil/SkinRestorer#36]
On the first try it was working properly fine on my end, the skin renders for me and the other players on our server. Yet, after relogging in, my skin and other's skin no longer works properly and it always shows Steve (only on my end/perspective). I've tried doing /skin clear and /skin refresh and then reapplying the skin (I tried both mojang and ely.by), it no longer works.

However, as I have stated earlier, it works perfectly fine on other player's perspective. I don't know what's the problem since it's not showing any logs on the console whenever I set my skin. (I'm using TLauncher btw)

**Comment by Suiranoil** [comment]
This might be an issue with TLauncher. Do you have any mods installed? From what i've heard TLauncher might automatically install custom mod to support their skin system which might interfere with official skins.

Also i would recommend to not use TLauncher as the company running it seems sketchy (there are plenty videos on yt about that). You could use [PrismLauncher](https://prismlauncher.org/) with offline account. It provides a much better ux, in my opinion. Here's an instruction on how to set it up: https://github.com/antunnitraj/Prism-Launcher-PolyMC-Offline-Bypass

**Comment by SnoopyCodeX** [comment]
Thank you! It's working fine again, I've migrated to Prism launcher. I think you're right, the conflicting mod was TLauncher's custom skin and cape built-in mod. Thank you for the recommendation to use PrismLauncher instead. [I'm closing this issue now]
