### ISSUE TITLE
Failed Loading Skin on Minecraft 1.16.5

### ISSUE THREAD

**Issue by masterLazy** [Suiranoil/SkinRestorer#37]
Minecraft Version: 1.16.5

Mod Verison: 1.0.4 (from CurseForge)

Fabric Version: 0.42.0

I installed the mod for my fabric server, and I tried this command:

```
/skin set web slim "https://littleskin.cn/raw/511796"
```

I got the message "You need to reconnect to apply the skin", but after reconnecting the skin is still unavaliable.

I also tried commands begin with `/skin set mojang`, they did work.

Is this a bug or I did something wrong? Please help.

**Comment by masterLazy** [comment]
And server didn't print any errors on the console.

**Comment by Suiranoil** [comment]
From my testing it seems that the site you are using cannot be accessed by mineskin (service that is used for url skins). Can you try to upload your skin to other image hosting website? For example, imgur.com, imgbb.com or others

**Comment by masterLazy** [comment]
Thanks! The problem has been fixed.
