### ISSUE TITLE
Prevents exiting program since v2.2.0 for fabric

### ISSUE THREAD

**Issue by Dastan21** [Suiranoil/SkinRestorer#41]
The version 2.2.0 for fabric 1.21 (tested with 1.21.3/1.21.4) prevents the program from exiting when the server is stopped.
It works fine in 2.1.0.

### How to reproduce

- Setup a fabric server in 1.21.4
- Add Fabric API and SkinRestorer 2.2.0
- Start the server
- Type "stop" in the console -> the server stops and saves the worlds
- The console is still running the program and waiting for inputs

**Comment by LOStacNet** [comment]
I also have this problem when using version 2.2.0 for fabric 1.20 in 1.20.1 server and Fabric Loader 0.16.9.The server program still run after /stop

**Comment by Suiranoil** [comment]
fixed in v2.2.1
