### ISSUE TITLE
Invalid signature for public profile key Minecraft

### ISSUE THREAD

**Issue by ghost** [Suiranoil/SkinRestorer#6]
Whenever I try to join the server with SkinRestorer, there's an error which mentions "Invalid signature for public profile key", the mods in my server (excluding SkinRestorer) are..

- architectury-6.5.69-fabric.jar

- fabric-api-0.75.0+1.19.2.jar

- identity-2.6.1-1.19.1-fabric.jar

- iris-mc1.19.2-1.5.2.jar

- lithium-fabric-mc1.19.2-0.10.4.jar

- Terralith_v2.3.6.jar

(Fabric 1.19.2)

**Comment by bbz-233** [comment]
你或者服务器处于离线模式或者服务器没开正版验证，这两者之一成立的同时服务器没加FreedomChat之类的插件时，会出现这类问题，跟你装了什么mod无关

**Comment by Suiranoil** [comment]
Cannot reproduce
